spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/reservas  # Base de datos del docker-compose
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Azure AD Configuration for Development (DISABLED)
  cloud:
    azure:
      compatibility-verifier:
        enabled: false  # Disable compatibility check
      active-directory:
        enabled: false  # Disable for local development

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: reservas.muni.pz@gmail.com
    password: wjca dbyg aixv hkmg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# JWT Configuration
app:
  jwt:
    secret: myDevSecretKey123456789012345678901234567890
    expiration: 86400000 # 24 hours
    issuer: reservas-municipales-dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,env
  endpoint:
    health:
      show-details: always

# Logging for development
logging:
  level:
    cr.una.reservas_municipales: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE