spring:
  datasource:
    # When running the application from the host (mvnd/mvn/IDE) and exposing Postgres with docker-compose
    # the host should be 'localhost' and the container port is forwarded to 5433 on the host.
    url: jdbc:postgresql://localhost:5433/reservas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Email Configuration (usando MailHog para testing local)
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  security:
    user:
      name: testuser
      password: testpass

  # Azure AD Configuration
  cloud:
    azure:
      compatibility-verifier:
        enabled: false  # Disable compatibility check for now
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_TENANT_ID:your-tenant-id-here}
        credential:
          client-id: ${AZURE_CLIENT_ID:your-client-id-here}
          client-secret: ${AZURE_CLIENT_SECRET:your-client-secret-here}
        app-id-uri: ${AZURE_APP_ID_URI:api://your-app-id-here}

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
    expiration: 86400000 # 24 hours
    issuer: reservas-municipales
  
  # Reservation Cancellation Policy
  reservations:
    cancellation:
      min-hours-before: 24  # Minimum hours before reservation start to allow cancellation

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# Logging
logging:
  level:
    cr.una.reservas_municipales: DEBUG
    org.springframework.security: DEBUG
