version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: reservas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reservas"]
      interval: 10s
      timeout: 5s
      retries: 5
